const data = {
  'id': 'shop/new/all-new',
  'name': 'All New',
  'categoryType': 'subcat',
  'groups': [
    {
      'id': 'nova-bath-accessories-b3581',
      'name': 'Nova Bath Accessories',
      'links': {
        'www': 'https://www.westelm.com/products/nova-bath-accessories-b3581/',
      },
      'priceRange': {
        'selling': {
          'high': 110,
          'low': 20,
        },
      },
      'thumbnail': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'thumbnail',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/nova-bath-accessories-1-m.jpg',
        'height': 363,
      },
      'hero': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'hero',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/nova-bath-accessories-1-m.jpg',
        'height': 363,
      },
      'images': [
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/nova-bath-accessories-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/nova-bath-accessories-3-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/nova-bath-accessories-4-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/nova-bath-accessories-2-m.jpg',
          'height': 363,
        },
      ],
      'swatches': [],
      'messages': [],
      'flags': [
        {
          'bopisSuppress': false,
          'rank': 11,
          'id': 'new_colors',
        },
      ],
      'reviews': {
        'recommendationCount': 0,
        'likelihood': 0,
        'reviewCount': 0,
        'averageRating': 0,
        'id': 'nova-bath-accessories-b3581',
        'type': 'GROUP_REVIEWS',
      },
    },
    {
      'id': 'ume-bath-accessories-b3584',
      'name': 'Ume Bath Accessories',
      'links': {
        'www': 'https://www.westelm.com/products/ume-bath-accessories-b3584/',
      },
      'priceRange': {
        'selling': {
          'high': 95,
          'low': 22,
        },
      },
      'thumbnail': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'thumbnail',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/ume-bath-accessories-m.jpg',
        'height': 363,
      },
      'hero': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'hero',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/ume-bath-accessories-m.jpg',
        'height': 363,
      },
      'images': [
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/ume-bath-accessories-4-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/ume-bath-accessories-3-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/ume-bath-accessories-2-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202117/0200/ume-bath-accessories-1-m.jpg',
          'height': 363,
        },
      ],
      'swatches': [],
      'messages': [],
      'flags': [
        {
          'bopisSuppress': false,
          'rank': 11,
          'id': 'new_colors',
        },
      ],
      'reviews': {
        'recommendationCount': 0,
        'likelihood': 0,
        'reviewCount': 0,
        'averageRating': 0,
        'id': 'ume-bath-accessories-b3584',
        'type': 'GROUP_REVIEWS',
      },
    },
    {
      'id': 'sono-bath-accessories-b3658',
      'name': 'Sono Bath Accessories',
      'links': {
        'www': 'https://www.westelm.com/products/sono-bath-accessories-b3658/',
      },
      'priceRange': {
        'selling': {
          'high': 85,
          'low': 17,
        },
      },
      'thumbnail': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'thumbnail',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202131/0172/sono-bath-accessories-m.jpg',
        'height': 363,
      },
      'hero': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'hero',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202131/0172/sono-bath-accessories-m.jpg',
        'height': 363,
      },
      'images': [
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0636/sono-bath-accessories-3-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0636/sono-bath-accessories-2-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0636/sono-bath-accessories-4-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0636/sono-bath-accessories-6-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0636/sono-bath-accessories-m.jpg',
          'height': 363,
        },
      ],
      'swatches': [],
      'messages': [],
      'flags': [
        {
          'bopisSuppress': false,
          'rank': 11,
          'id': 'new_colors',
        },
      ],
      'reviews': {
        'recommendationCount': 0,
        'likelihood': 0,
        'reviewCount': 0,
        'averageRating': 0,
        'id': 'sono-bath-accessories-b3658',
        'type': 'GROUP_REVIEWS',
      },
    },
    {
      'id': 'brushed-herringbone-throw-t5792',
      'name': 'Brushed Herringbone Throw',
      'links': {
        'www': 'https://www.westelm.com/products/brushed-herringbone-throw-t5792/',
      },
      'price': {
        'regular': 70,
        'selling': 70,
      },
      'thumbnail': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'thumbnail',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/1030/brushed-herringbone-throw-m.jpg',
        'height': 363,
      },
      'hero': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'hero',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/1030/brushed-herringbone-throw-m.jpg',
        'height': 363,
      },
      'images': [
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/1031/brushed-herringbone-throw-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202135/0018/brushed-herringbone-throw-m.jpg',
          'height': 363,
        },
      ],
      'swatches': [],
      'messages': [],
      'flags': [
        {
          'bopisSuppress': false,
          'rank': 4,
          'id': 'freeship',
        },
        {
          'bopisSuppress': false,
          'rank': 11,
          'id': 'new_colors',
        },
      ],
      'reviews': {
        'recommendationCount': 0,
        'likelihood': 0,
        'reviewCount': 0,
        'averageRating': 0,
        'id': 'brushed-herringbone-throw-t5792',
        'type': 'GROUP_REVIEWS',
      },
    },
    {
      'id': 'chunky-knit-throw-t6259',
      'name': 'Chunky Knit Throw',
      'links': {
        'www': 'https://www.westelm.com/products/chunky-knit-throw-t6259/',
      },
      'price': {
        'regular': 150,
        'selling': 150,
      },
      'thumbnail': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'thumbnail',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202131/0101/chunky-knit-throw-3-m.jpg',
        'height': 363,
      },
      'hero': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'hero',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202131/0101/chunky-knit-throw-3-m.jpg',
        'height': 363,
      },
      'images': [
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202131/0101/chunky-knit-throw-1-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202131/0101/chunky-knit-throw-m.jpg',
          'height': 363,
        },
      ],
      'swatches': [],
      'messages': [],
      'flags': [
        {
          'bopisSuppress': false,
          'rank': 3,
          'id': 'newcore',
        },
        {
          'bopisSuppress': false,
          'rank': 4,
          'id': 'freeship',
        },
        {
          'bopisSuppress': false,
          'rank': 10,
          'id': 'handcrafted',
        },
      ],
      'reviews': {
        'recommendationCount': 0,
        'likelihood': 0,
        'reviewCount': 0,
        'averageRating': 0,
        'id': 'chunky-knit-throw-t6259',
        'type': 'GROUP_REVIEWS',
      },
    },
    {
      'id': 'cotton-linen-velvet-corners-oversized-lumbar-pillow-cover-w4198',
      'name': 'Cotton Linen & Velvet Corners Oversized Lumbar Pillow Cover',
      'links': {
        'www': 'https://www.westelm.com/products/cotton-linen-velvet-corners-oversized-lumbar-pillow-cover-w4198/',
      },
      'price': {
        'regular': 47.5,
        'selling': 47.5,
      },
      'thumbnail': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'thumbnail',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0074/cotton-linen-velvet-corners-oversized-lumbar-pillow-cover-1-m.jpg',
        'height': 363,
      },
      'hero': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'hero',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0074/cotton-linen-velvet-corners-oversized-lumbar-pillow-cover-1-m.jpg',
        'height': 363,
      },
      'images': [
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0074/cotton-linen-velvet-corners-oversized-lumbar-pillow-cover-5-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0074/cotton-linen-velvet-corners-oversized-lumbar-pillow-cover-6-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0074/cotton-linen-velvet-corners-oversized-lumbar-pillow-cover-3-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0074/cotton-linen-velvet-corners-oversized-lumbar-pillow-cover-4-m.jpg',
          'height': 363,
        },
      ],
      'swatches': [],
      'messages': [],
      'flags': [
        {
          'bopisSuppress': false,
          'rank': 3,
          'id': 'newcore',
        },
        {
          'bopisSuppress': false,
          'rank': 4,
          'id': 'freeship',
        },
        {
          'bopisSuppress': false,
          'rank': 8,
          'id': 'handmade',
        },
        {
          'bopisSuppress': false,
          'rank': 9,
          'id': 'fairTrade',
        },
        {
          'bopisSuppress': false,
          'rank': 12,
          'id': 'newSize',
        },
      ],
      'reviews': {
        'recommendationCount': 0,
        'likelihood': 0,
        'reviewCount': 0,
        'averageRating': 0,
        'id': 'cotton-linen-velvet-corners-oversized-lumbar-pillow-cover-w4198',
        'type': 'GROUP_REVIEWS',
      },
    },
    {
      'id': 'classic-cotton-velvet-oversized-lumbar-pillow-cover-w4199',
      'name': 'Classic Cotton Velvet Oversized Lumbar Pillow Cover',
      'links': {
        'www': 'https://www.westelm.com/products/classic-cotton-velvet-oversized-lumbar-pillow-cover-w4199/',
      },
      'price': {
        'regular': 59.5,
        'selling': 59.5,
      },
      'thumbnail': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'thumbnail',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0074/classic-cotton-velvet-oversized-lumbar-pillow-cover-1-m.jpg',
        'height': 363,
      },
      'hero': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'hero',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0074/classic-cotton-velvet-oversized-lumbar-pillow-cover-1-m.jpg',
        'height': 363,
      },
      'images': [
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0074/classic-cotton-velvet-oversized-lumbar-pillow-cover-3-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202130/0074/classic-cotton-velvet-oversized-lumbar-pillow-cover-m.jpg',
          'height': 363,
        },
      ],
      'swatches': [],
      'messages': [],
      'flags': [
        {
          'bopisSuppress': false,
          'rank': 3,
          'id': 'newcore',
        },
        {
          'bopisSuppress': false,
          'rank': 4,
          'id': 'freeship',
        },
        {
          'bopisSuppress': false,
          'rank': 9,
          'id': 'fairTrade',
        },
        {
          'bopisSuppress': false,
          'rank': 12,
          'id': 'newSize',
        },
      ],
      'reviews': {
        'recommendationCount': 0,
        'likelihood': 0,
        'reviewCount': 0,
        'averageRating': 0,
        'id': 'classic-cotton-velvet-oversized-lumbar-pillow-cover-w4199',
        'type': 'GROUP_REVIEWS',
      },
    },
    {
      'id': 'crewel-wavy-cutouts-pillow-covers-t5140',
      'name': 'Crewel Wavy Cutouts Pillow Covers',
      'links': {
        'www': 'https://www.westelm.com/products/crewel-wavy-cutouts-pillow-covers-t5140/',
      },
      'priceRange': {
        'selling': {
          'high': 94,
          'low': 47.5,
        },
      },
      'thumbnail': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'thumbnail',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0508/crewel-wavy-cutouts-pillow-covers-1-m.jpg',
        'height': 363,
      },
      'hero': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'hero',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0508/crewel-wavy-cutouts-pillow-covers-1-m.jpg',
        'height': 363,
      },
      'images': [
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0511/crewel-wavy-cutouts-pillow-covers-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0511/crewel-wavy-cutouts-pillow-covers-1-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0512/crewel-wavy-cutouts-pillow-covers-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0514/crewel-wavy-cutouts-pillow-covers-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202115/0024/crewel-wavy-cutouts-pillow-covers-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202115/0093/crewel-wavy-cutouts-pillow-covers-m.jpg',
          'height': 363,
        },
      ],
      'swatches': [],
      'messages': [],
      'flags': [
        {
          'bopisSuppress': false,
          'rank': 3,
          'id': 'newcore',
        },
        {
          'bopisSuppress': false,
          'rank': 4,
          'id': 'freeship',
        },
        {
          'bopisSuppress': false,
          'rank': 8,
          'id': 'handmade',
        },
        {
          'bopisSuppress': false,
          'rank': 10,
          'id': 'handcrafted',
        },
      ],
      'reviews': {
        'recommendationCount': 0,
        'likelihood': 0,
        'reviewCount': 0,
        'averageRating': 0,
        'id': 'crewel-wavy-cutouts-pillow-covers-t5140',
        'type': 'GROUP_REVIEWS',
      },
    },
    {
      'id': 'crewel-balancing-shapes-pillow-covers-t4799',
      'name': 'Crewel Balancing Shapes Pillow Covers',
      'links': {
        'www': 'https://www.westelm.com/products/crewel-balancing-shapes-pillow-covers-t4799/',
      },
      'priceRange': {
        'selling': {
          'high': 94,
          'low': 47.5,
        },
      },
      'thumbnail': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'thumbnail',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0500/crewel-balancing-shapes-pillow-covers-1-m.jpg',
        'height': 363,
      },
      'hero': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'hero',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0500/crewel-balancing-shapes-pillow-covers-1-m.jpg',
        'height': 363,
      },
      'images': [
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0500/crewel-balancing-shapes-pillow-covers-2-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0501/crewel-balancing-shapes-pillow-covers-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0504/crewel-balancing-shapes-pillow-covers-2-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0504/crewel-balancing-shapes-pillow-covers-3-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202115/0280/crewel-balancing-shapes-pillow-covers-m.jpg',
          'height': 363,
        },
      ],
      'swatches': [],
      'messages': [],
      'flags': [
        {
          'bopisSuppress': false,
          'rank': 3,
          'id': 'newcore',
        },
        {
          'bopisSuppress': false,
          'rank': 4,
          'id': 'freeship',
        },
        {
          'bopisSuppress': false,
          'rank': 8,
          'id': 'handmade',
        },
        {
          'bopisSuppress': false,
          'rank': 10,
          'id': 'handcrafted',
        },
      ],
      'reviews': {
        'recommendationCount': 0,
        'likelihood': 0,
        'reviewCount': 0,
        'averageRating': 0,
        'id': 'crewel-balancing-shapes-pillow-covers-t4799',
        'type': 'GROUP_REVIEWS',
      },
    },
    {
      'id': 'crewel-shadow-bars-pillow-covers-t4807',
      'name': 'Crewel Shadow Bars Pillow Covers',
      'links': {
        'www': 'https://www.westelm.com/products/crewel-shadow-bars-pillow-covers-t4807/',
      },
      'priceRange': {
        'selling': {
          'high': 94,
          'low': 47.5,
        },
      },
      'thumbnail': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'thumbnail',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202127/0273/crewel-shadow-bars-pillow-covers-m.jpg',
        'height': 363,
      },
      'hero': {
        'size': 'm',
        'meta': '',
        'alt': '',
        'rel': 'hero',
        'width': 363,
        'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202127/0273/crewel-shadow-bars-pillow-covers-m.jpg',
        'height': 363,
      },
      'images': [
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0486/crewel-shadow-bars-pillow-covers-1-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0486/crewel-shadow-bars-pillow-covers-2-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0486/crewel-shadow-bars-pillow-covers-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202129/0504/crewel-balancing-shapes-pillow-covers-3-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202115/0186/crewel-shadow-bars-pillow-covers-m.jpg',
          'height': 363,
        },
        {
          'size': 'm',
          'meta': '',
          'alt': '',
          'rel': 'althero',
          'width': 363,
          'href': 'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202115/0210/crewel-shadow-bars-pillow-covers-m.jpg',
          'height': 363,
        },
      ],
      'swatches': [],
      'messages': [],
      'flags': [
        {
          'bopisSuppress': false,
          'rank': 3,
          'id': 'newcore',
        },
        {
          'bopisSuppress': false,
          'rank': 4,
          'id': 'freeship',
        },
        {
          'bopisSuppress': false,
          'rank': 8,
          'id': 'handmade',
        },
      ],
      'reviews': {
        'recommendationCount': 0,
        'likelihood': 0,
        'reviewCount': 0,
        'averageRating': 0,
        'id': 'crewel-shadow-bars-pillow-covers-t4807',
        'type': 'GROUP_REVIEWS',
      },
    },
  ],
  'totalPages': 103,
  'categories': [],
}

export default data